# -*- coding: utf-8 -*-
"""ML_cnn_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Zd61xFH-SheYYHEhnm4LcmyLR7z4Zo
"""



"""# **Handwritten digit classification**

**Load data from kaggle hub**
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("olafkrastovski/handwritten-digits-0-9")

print("Path to dataset files:", path)

"""**List all sub directories inside main folder**"""

import os
print(os.listdir(path))

"""**Display 5 images in each folder**"""

import matplotlib.pyplot as plt
from PIL import Image
i=1
plt.figure(figsize=(12,10))
for class_name in os.listdir(path):
  class_path = os.path.join(path,class_name)
  if os.path.isdir(class_path):
    images = os.listdir(class_path)[:5]
    for img in images:
      img_path = os.path.join(class_path,img)
      img = Image.open(img_path)

      plt.subplot(10,5,i)
      plt.imshow(img)
      plt.title(class_name)
      plt.axis('off')

      i+=1
plt.tight_layout()
plt.show()

"""**find how many images we have in each folder**"""

for label in os.listdir(path):
  class_path=os.path.join(path,label)
  count = len(os.listdir(class_path))
  print(label,'-->',count)

"""**create a dataframe which includes imag_path and label**"""

import pandas as pd
df =[]
for label in os.listdir(path):
  class_path = os.path.join(path,label)
  images = os.listdir(class_path)
  for img in images:
    img_path = os.path.join(class_path,img)
    df.append([img_path,label])
data = pd.DataFrame(df,columns=['img_path','label'])

"""**Shuffle images**"""

data = data.sample(frac=1,random_state=42).reset_index()
data

data

"""**Split data for training ,testing and Validation**"""

train_size = int(0.7*len(data))
test_size= int(0.15*len(data))
val_size = int(0.15*len(data))
print('train_size',train_size)
print('test_size',test_size)
print('val_size',val_size)

train_data = data.iloc[:train_size]
print('train_data',len(train_data))
test_data = data.iloc[train_size:train_size+test_size]
print('test_data',len(test_data))
val_data = data.iloc[train_size+val_size:]
print('val_data',len(val_data))

"""**Image preprocessing**"""

img = data.loc[0,'img_path']
img = Image.open(img)
height,width = img.size
print(height,width)

batch_size= 32
img_height=128
img_width=128

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_generator = ImageDataGenerator(
    rescale = 1.0/255 , #Normalization:pixel value will be converted to 0 and 1
    rotation_range=40, #rotates image upto 40 degree
    width_shift_range = 0.2, # moves an image to left and right by 20%
    height_shift_range =0.2 ,# moves an image up and down by 20%
    shear_range=0.2, # slant the image
    zoom_range=0.2,horizontal_flip=True,fill_mode='nearest')

train_generator = data_generator.flow_from_dataframe(
    dataframe = train_data,
    x_col ='img_path',
    y_col ='label',
    target_size=(img_height,img_width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True,
    seed = 42
)

test_generator = data_generator.flow_from_dataframe(
    dataframe = test_data,
    x_col ='img_path',
    y_col ='label',
    target_size=(img_height,img_width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True,
    seed = 42
)

val_generator = data_generator.flow_from_dataframe(
    dataframe = val_data,
    x_col ='img_path',
    y_col ='label',
    target_size=(img_height,img_width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True,
    seed = 42
)

for image_batch,labels_batch in train_generator:
  print(f'train_shape:{image_batch.shape} (Batches={len(train_generator)})')
  break

for image_batch,labels_batch in test_generator:
  print(f'train_shape:{image_batch.shape} (Batches={len(test_generator)})')
  break

for image_batch,labels_batch in val_generator:
  print(f'train_shape:{image_batch.shape} (Batches={len(val_generator)})')
  break

"""# Model Building"""

from tensorflow.keras import layers , models
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy

n_classes=10
cnn_model =models.Sequential([
    layers.Input(shape=(128,128,3)),
    layers.Conv2D(32,kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(n_classes,activation='softmax')
])

cnn_model.compile(loss=categorical_crossentropy,optimizer=Adam(),metrics=['accuracy'])

cnn = cnn_model.fit(train_generator,epochs=4,validation_data=val_generator,
                    verbose=1)

train_loss,train_accuracy = cnn_model.evaluate(train_generator,verbose=1)
print("train_loss",train_loss,"train_accuracy",train_accuracy)

test_loss,test_accuracy = cnn_model.evaluate(test_generator,verbose=1)
print("test_loss",test_loss,"test_accuracy",test_accuracy)

from tensorflow.keras.preprocessing import image
import numpy as np

img_path = "three.jpg"

# Load image
img = image.load_img(img_path, target_size=(128, 128))  # same as training

# Convert to array
img_array = image.img_to_array(img)

# Normalize
img_array = img_array / 255.0

# Add batch dimension
img_array = np.expand_dims(img_array, axis=0)

prediction = cnn_model.predict(img_array)
print(prediction)

predicted_class = np.argmax(prediction)

print("Predicted Class:", predicted_class)

